
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.1/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
  -
    kind: "find-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-4.1/Modules/CMakeMinGWFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:2 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "mingw32-make.exe"
    candidate_directories:
      - "C:/Users/oman/AppData/Local/Temp/.tmpVNlKqB/"
      - "C:/Windows/System32/"
      - "C:/Windows/"
      - "C:/Windows/System32/wbem/"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/"
      - "C:/Windows/System32/OpenSSH/"
      - "C:/ProgramData/chocolatey/bin/"
      - "D:/Program Files/Git/cmd/"
      - "C:/Program Files/dotnet/"
      - "C:/Program Files/Cloudflare/Cloudflare WARP/"
      - "D:/Program Files/nodejs/"
      - "D:/Program Files/Go/bin/"
      - "C:/Program Files (x86)/cloudflared/"
      - "C:/Program Files/CMake/bin/"
      - "C:/Users/oman/AppData/Local/Microsoft/WindowsApps/"
      - "C:/Users/oman/AppData/Local/Programs/Microsoft VS Code/bin/"
      - "C:/Users/oman/.dotnet/tools/"
      - "D:/OllamaDir/"
      - "D:/OLLAMAMODELS/"
      - "C:/Users/oman/.lmstudio/bin/"
      - "C:/Users/oman/AppData/Roaming/npm/"
      - "C:/Users/oman/go/bin/"
      - "C:/Users/oman/AppData/Local/GitHubDesktop/bin/"
      - "C:/Users/oman/.vscode/extensions/openai.chatgpt-0.4.6-win32-x64/bin/windows-x86_64/"
      - "/REGISTRY-NOTFOUND/bin/"
      - "c:/MinGW/bin/"
      - "/MinGW/bin/"
      - "/REGISTRY-NOTFOUND/MinGW/bin/"
    searched_directories:
      - "C:/Users/oman/AppData/Local/Temp/.tmpVNlKqB/mingw32-make.exe.com"
      - "C:/Users/oman/AppData/Local/Temp/.tmpVNlKqB/mingw32-make.exe"
      - "C:/Windows/System32/mingw32-make.exe.com"
      - "C:/Windows/System32/mingw32-make.exe"
      - "C:/Windows/mingw32-make.exe.com"
      - "C:/Windows/mingw32-make.exe"
      - "C:/Windows/System32/wbem/mingw32-make.exe.com"
      - "C:/Windows/System32/wbem/mingw32-make.exe"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/mingw32-make.exe.com"
      - "C:/Windows/System32/WindowsPowerShell/v1.0/mingw32-make.exe"
      - "C:/Windows/System32/OpenSSH/mingw32-make.exe.com"
      - "C:/Windows/System32/OpenSSH/mingw32-make.exe"
      - "C:/ProgramData/chocolatey/bin/mingw32-make.exe.com"
      - "C:/ProgramData/chocolatey/bin/mingw32-make.exe"
      - "D:/Program Files/Git/cmd/mingw32-make.exe.com"
      - "D:/Program Files/Git/cmd/mingw32-make.exe"
      - "C:/Program Files/dotnet/mingw32-make.exe.com"
      - "C:/Program Files/dotnet/mingw32-make.exe"
      - "C:/Program Files/Cloudflare/Cloudflare WARP/mingw32-make.exe.com"
      - "C:/Program Files/Cloudflare/Cloudflare WARP/mingw32-make.exe"
      - "D:/Program Files/nodejs/mingw32-make.exe.com"
      - "D:/Program Files/nodejs/mingw32-make.exe"
      - "D:/Program Files/Go/bin/mingw32-make.exe.com"
      - "D:/Program Files/Go/bin/mingw32-make.exe"
      - "C:/Program Files (x86)/cloudflared/mingw32-make.exe.com"
      - "C:/Program Files (x86)/cloudflared/mingw32-make.exe"
      - "C:/Program Files/CMake/bin/mingw32-make.exe.com"
      - "C:/Program Files/CMake/bin/mingw32-make.exe"
      - "C:/Users/oman/AppData/Local/Microsoft/WindowsApps/mingw32-make.exe.com"
      - "C:/Users/oman/AppData/Local/Microsoft/WindowsApps/mingw32-make.exe"
      - "C:/Users/oman/AppData/Local/Programs/Microsoft VS Code/bin/mingw32-make.exe.com"
      - "C:/Users/oman/AppData/Local/Programs/Microsoft VS Code/bin/mingw32-make.exe"
      - "C:/Users/oman/.dotnet/tools/mingw32-make.exe.com"
      - "C:/Users/oman/.dotnet/tools/mingw32-make.exe"
      - "D:/OllamaDir/mingw32-make.exe.com"
      - "D:/OllamaDir/mingw32-make.exe"
      - "D:/OLLAMAMODELS/mingw32-make.exe.com"
      - "D:/OLLAMAMODELS/mingw32-make.exe"
      - "C:/Users/oman/.lmstudio/bin/mingw32-make.exe.com"
      - "C:/Users/oman/.lmstudio/bin/mingw32-make.exe"
      - "C:/Users/oman/AppData/Roaming/npm/mingw32-make.exe.com"
      - "C:/Users/oman/AppData/Roaming/npm/mingw32-make.exe"
      - "C:/Users/oman/go/bin/mingw32-make.exe.com"
      - "C:/Users/oman/go/bin/mingw32-make.exe"
      - "C:/Users/oman/AppData/Local/GitHubDesktop/bin/mingw32-make.exe.com"
      - "C:/Users/oman/AppData/Local/GitHubDesktop/bin/mingw32-make.exe"
      - "C:/Users/oman/.vscode/extensions/openai.chatgpt-0.4.6-win32-x64/bin/windows-x86_64/mingw32-make.exe.com"
      - "C:/Users/oman/.vscode/extensions/openai.chatgpt-0.4.6-win32-x64/bin/windows-x86_64/mingw32-make.exe"
      - "/REGISTRY-NOTFOUND/bin/mingw32-make.exe.com"
      - "/REGISTRY-NOTFOUND/bin/mingw32-make.exe"
      - "c:/MinGW/bin/mingw32-make.exe.com"
      - "c:/MinGW/bin/mingw32-make.exe"
      - "/MinGW/bin/mingw32-make.exe.com"
      - "/MinGW/bin/mingw32-make.exe"
      - "/REGISTRY-NOTFOUND/MinGW/bin/mingw32-make.exe.com"
      - "/REGISTRY-NOTFOUND/MinGW/bin/mingw32-make.exe"
    found: false
    search_context:
      ENV{PATH}:
        - "C:\\Users\\oman\\AppData\\Local\\Temp\\.tmpVNlKqB"
        - "C:\\WINDOWS\\system32"
        - "C:\\WINDOWS"
        - "C:\\WINDOWS\\System32\\Wbem"
        - "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\"
        - "C:\\WINDOWS\\System32\\OpenSSH\\"
        - "C:\\ProgramData\\chocolatey\\bin"
        - "D:\\Program Files\\Git\\cmd"
        - "C:\\Program Files\\dotnet\\"
        - "C:\\Program Files\\Cloudflare\\Cloudflare WARP\\"
        - "D:\\Program Files\\nodejs\\"
        - "D:\\Program Files\\Go\\bin"
        - "C:\\Program Files (x86)\\cloudflared\\"
        - "C:\\Program Files\\CMake\\bin"
        - "C:\\Users\\oman\\AppData\\Local\\Microsoft\\WindowsApps"
        - "C:\\Users\\oman\\AppData\\Local\\Programs\\Microsoft VS Code\\bin"
        - "C:\\Users\\oman\\.dotnet\\tools"
        - "D:\\OllamaDir"
        - "D:\\OLLAMAMODELS"
        - "C:\\Users\\oman\\.lmstudio\\bin"
        - "C:\\Users\\oman\\AppData\\Roaming\\npm"
        - "C:\\Users\\oman\\go\\bin"
        - "C:\\Users\\oman\\AppData\\Local\\GitHubDesktop\\bin"
        - "c:\\Users\\oman\\.vscode\\extensions\\openai.chatgpt-0.4.6-win32-x64\\bin\\windows-x86_64"
...
